language: go

go:
- "1.10.x"
- "1.11.x"

services:
- docker

sudo: false

notifications:
  email:
    on_success: never

branches:
  only:
  - master
  - develop
  - test-tag
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

install:
  - go get -tags="dev" -v github.com/k-box/k-link-registry/klinkregistry

before_script:
  - cd ui
  - yarn
  - yarn build
  - cd ..

script:
  # - go vet -tags="dev" -v github.com/k-box/k-link-registry/klinkregistry
  - go vet -tags="dev" $(go list ./... | grep -v /vendor/)
  - go test -tags="dev" -race $(go list ./... | grep -v /vendor/) -v -coverprofile .testCoverage.txt
  - go get github.com/shurcooL/vfsgen/cmd/vfsgendev
  - go generate github.com/k-box/k-link-registry/assets
  - go get github.com/inconshreveable/mousetrap
  - GOOS=linux   GOARCH=amd64         go build -tags "netgo" -o ./dist/klinkregistry.bin github.com/k-box/k-link-registry/klinkregistry

before_deploy:
  - GOOS=linux   GOARCH=amd64         go build -tags "netgo" -o ./dist/klinkregistry-linux-x64.bin github.com/k-box/k-link-registry/klinkregistry
  - GOOS=windows GOARCH=amd64         go build -tags "netgo" -o ./dist/klinkregistry-win-x64.exe github.com/k-box/k-link-registry/klinkregistry

deploy:
  provider: releases
  api_key:
    secure: GcjTuXUJv4USZEtMTbCxCtvJGaxbOglt2ZCiSa0B0Qty0Dz4PSnWojJPeRaeZ7BSRltNU0gWGnD3Rnc4X5loeGP//B05GjuUtMtjHQc3zW2TEK4Z2Uik5zVVA4F2ry3vfCEIQIae8mr3EMRZoqilkGJzcojrrk0zepaMiNFDjJIKeQiGyNXb+RzuNVNrxsI5REtnu870dtYhMyShHzGhxkIrTV2WZvySpEEReWxqI5zrHdh8tsPwfTVyM07qGU0QwcyNq2pmPGRzZ9pfm/uNnoFUKgxBoQx9tu/F8GeapsrQuesI3tbS2d6jfhq0S1gjU2zblaADWPWCksv/JJCkZPqNzyBSXCSRKX9rCALQUkRXSPqZqKA88V+Y1GJnjR9zoz5nUUxPARQ2EH5amcj2AcJcTVlgHN2ryBIpRrQoAQDIqACtMW/TNwV4UqVp/G5g6tJNY7qU8nGKh37scydDJ5dnOvRBeB8KCHyw0MuFYegkUDw0sqPW55aU4uCwqjjHa0DcfExWMSM1d27ZwDjcJUE/FoSVFWg4Gb4hDfPWaHwDysXL4HwjnWZNdL3spC0kf9ClZz2cofonHnjmFYfhguAnmEucg/YnhuAuy56zPdXFOpfCe25mNIs1733D5gNTRK2gr9ahgKPYxvWzx0aRDHudM3IS6pMRH2yDwcutISw=
  file: 
    - "dist/klinkregistry-linux-x64.bin"
    - "dist/klinkregistry-win-x64.exe"
  skip_cleanup: true
  on:
    repo: k-box/k-link-registry
    tags: true
    go: "1.10.x"
