<template>
  <div class="box">
    <h3 v-if="application.id == 0" class="title is-3">New Application</h3>
    <h3 v-if="application.id != 0" class="title is-3">Edit Application: {{ application.name }}</h3>
    <form>
      <div class="field is-horizontal">
        <label for="name" class="field-label is-normal">Name</label>
        <div class="field-body">
          <div class="field">
            <div class="control is-expanded">
              <input id="name" v-model="application.name" type="text" class="input">
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <label for="owner" class="field-label is-normal">Owner</label>
        <div class="field-body">
          <div class="field is-narrow">
            <div class="control">
              <div class="select is-primary">
                <select id="owner" v-model="application.owner_id">
                  <option v-for="user in registrants" :key="user.id" :value="user.id">{{ user.name | user.email }}</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <label for="app_domain" class="field-label is-normal">App Domain</label>
        <div class="field-body">
          <div class="field">
            <div class="control is-expanded">
              <input id="domain" v-model="application.app_domain" type="text" class="input">
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <label for="token" class="field-label is-normal">Token</label>
        <div class="field-body">
          <div class="field">
            <div class="control is-expanded">
              <input id="token" placeholder="will be autogenerated" v-model="application.token" type="text" class="input" readonly>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <label class="field-label is-normal">Permissions</label>
        <div class="field-body">
          <div class="field is-narrow">
            <div class="control" v-for="permission in permissions" :key="permission.name">
              <label :for="permission.name" class="checkbox">
                <input :id="permission.name" :value="permission.name" v-model="application.permissions" type="checkbox">
                {{ permission.name }}
              </label>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <label for="active" class="field-label is-normal">Active</label>
        <div class="field-body">
          <div class="field is-narrow">
            <div class="control">
              <label class="checkbox">
                <input id="active" v-model="application.active" type="checkbox">
                Application can authenticate
              </label>
            </div>
          </div>
        </div>
      </div>

      <template v-if="!!application.id">
          <button @click="deleteApplication" class="is-pulled-right button is-danger">Delete</button>
          <button @click="updateApplication" class="button is-primary">Update</button>
        </template>
        <template v-else>
          <button @click="createApplication" class="button is-primary">Create</button>
        </template>
    </form>
  </div>
</template>

<script>
import * as api from "@/utils/api";
import store from "@/store";

console.log(store.state);

const baseApplication = {
  id: 0,
  owner_id: 0,
  name: "",
  app_domain: "",
  token: "",
  active: true,
  permissions: []
};

export default {
  name: "application",
  props: ["dependencies"],
  data: function() {
    return {
      application: {},
      permissions: [],
      registrants: [],
      errors: []
    };
  },
  created() {
    this.fetchData();
  },
  methods: {
    createApplication(event) {
      event.preventDefault();
      event.stopPropagation();

      api
        .newApplication(this.application)
        .then(() => {
          this.$showSuccess("Application created");
          this.$router.push({ name: "Applications" });
        })
        .catch(e => {
          this.$showError("Error creating the Application");
        });
    },
    updateApplication(event) {
      event.preventDefault();
      event.stopPropagation();

      api
        .updateApplication(this.application)
        .then(application => {
          this.$showSuccess("Application updated");
          this.$router.push({ name: "Applications" });
        })
        .catch(e => {
          this.$showError("Error updating the Application");
        });
    },
    deleteApplication(event) {
      event.preventDefault();
      event.stopPropagation();

      api
        .deleteApplication(this.application.id)
        .then(() => {
          this.$showSuccess("Application deleted");
          this.$router.push({ name: "Applications" });
        })
        .catch(e => {
          this.$showError("Error deleting the Application");
          console.log(e);
          this.errors.push(e);
        });
    },
    fetchData() {
      let applicationID = this.$route.params.id;

      // if we want to create a new user, load the default user instead of
      // querying the API
      if (applicationID === "new") {
        this.application = baseApplication;
        this.application.owner_id = store.state.user.id;
      } else {
        api
          .getApplication(applicationID)
          .then(application => {
            this.application = application;
          })
          .catch(e => {
            this.$showError("Error fetching Applications");
            this.errors.push(e);
          });
      }

      api
        .getPermissions()
        .then(permissions => {
          this.permissions = permissions;
        })
        .catch(e => {
          this.$showError("Error fetching Permissions");
          this.errors.push(e);
        });

      api
        .getRegistrants()
        .then(registrants => {
          this.registrants = registrants;
          console.log(registrants);
        })
        .catch(e => {
          this.$showError("Error fetching Registrants");
          this.errors.push(e);
        });
    }
  }
};
</script>
